### ISSUE TITLE
KeyError: 'polyphen_score'

### ISSUE THREAD

**Issue by park-brian** [CBIIT-CGBB/3DVizSNP#2]
Hello, I am running into the following error when running the script against the GBM_full_1.vep.vcf.gz file (sent via email):

```bash
python3 3DVizSNP.py -v GBM_full_1.vep.vcf.gz
Traceback (most recent call last):
  File "/server/scripts/3DVizSNP.py", line 767, in <module>
    main(cli().parse_args())   
  File "/server/scripts/3DVizSNP.py", line 736, in main
    vep_result = vep_output(variants, args)
  File "/server/scripts/3DVizSNP.py", line 207, in vep_output
    'PPscore': j["polyphen_score"]})
KeyError: 'polyphen_score'
```

It appears that VEP does not return polyphen_scores for some variants. To work around this, we can use the .get method instead of using square brackets. Eg:
```python
# line 199
row = pd.Series({'variant': var,
                'EnsID': gene_id,
                'SPID': sp,
                'PDBID': '',
                'mutaa': mutaa,
                'SIpred': j.get("sift_prediction"),
                'SIscore': j["sift_score"],
                'PPpred': j.get("polyphen_prediction"),
                'PPscore': j["polyphen_score"]})
```

can be replaced with:

```python
# line 199
row = pd.Series({'variant': var,
                'EnsID': gene_id,
                'SPID': sp,
                'PDBID': '',
                'mutaa': mutaa,
                'SIpred': j.get("sift_prediction"),
                'SIscore': j.get("sift_score"),
                'PPpred': j.get("polyphen_prediction"),
                'PPscore': j.get("polyphen_score")})
```

There might need to be further modifications in other places.

**Comment by park-brian** [comment]
If there are other places in the script which expect the PPscore and SIscore keys to be set, then we can also specify a default value as the second argument to `dict.get(..)`.

**Comment by park-brian** [comment]
Thanks, this has been resolved.
